version: "3.3"
services:
  app:
    build:
      args:
        user: myapi
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: myapi
    container_name: myapi-app
    restart: unless-stopped
    working_dir: /var/www/
    links:
      - db
    volumes:
      - ./:/var/www
    networks:
      - myapi

  db:
    image: mysql:5.7
    container_name: myapi-db
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - myapi

  nginx:
    image: nginx:alpine
    container_name: myapi-nginx
    restart: unless-stopped
    links:
      - db
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - myapi

networks:
  myapi:
    driver: bridge
